remote_theme: daattali/beautiful-jekyll@5.0.0

#
# Header
#
navbar-links:
  Locations: locations
  Characters:
    - Izhi: npcs/Izhi
  Organizations:
    - K'anchay Order: organizations/KanchayOrder
  Players:
    - Brother Gromag: players/BrotherGromag
    - Caltrop Bloodless: players/CaltropBloodless
    - Gluteus Maximus: players/GluteusMaximus
  Character Sheets:
    - Brother Gromag: https://www.dndbeyond.com/profile/Sirnik/characters/27153228
    - Caltrop Bloodless: https://www.dndbeyond.com/profile/Rycosso/characters/27153025
    - Gluteus Maximus: https://www.dndbeyond.com/profile/lilvin/characters/29239078
  Classes:
    - Artificer: https://www.dndbeyond.com/classes/artificer
    - Barbarian: https://www.dndbeyond.com/classes/barbarian
    - Blood Hunter: https://www.dndbeyond.com/classes/blood-hunter
    - Bard: https://www.dndbeyond.com/classes/bard
    - Cleric: https://www.dndbeyond.com/classes/cleric
    - Druid: https://www.dndbeyond.com/classes/druid
    - Fighter: https://www.dndbeyond.com/classes/fighter
    - Monk: https://www.dndbeyond.com/classes/monk
    - Paladin: https://www.dndbeyond.com/classes/paladin
    - Ranger: https://www.dndbeyond.com/classes/ranger
    - Rogue: https://www.dndbeyond.com/classes/rogue
    - Sorcerer: https://www.dndbeyond.com/classes/sorcerer
    - Warlock: https://www.dndbeyond.com/classes/warlock
    - Wizard: https://www.dndbeyond.com/classes/wizard
  Resources:
    - Campaign: https://www.dndbeyond.com/campaigns/994863
    - Player's Handbook: https://www.dndbeyond.com/sources/phb
    - Feats: https://www.dndbeyond.com/feats
    - Sword Types: http://myarmoury.com/feature_oakeshott2.html

#
# Footer
#
author: Tom Manner
social-network-links:
  email: tom.s.manner@gmail.com
  github: tsmanner

